initial pipeline additons
Shuffle/Shuffle pull request #1373
Opened 2024-04-25 12:45 UTC by satti-hari-krishna-reddy

2024-04-25 13:32 UTC, 0x0elliot requested changes

2024-04-25 13:32 UTC, 0x0elliot commented on functions/onprem/orborus/orborus.go
Why don't you have an environment variable that signifies that the user wants to use tenzir?

2024-04-25 13:42 UTC, 0x0elliot commented
If i were you, I would have tried to figure out if there is a way to add the tenzir configuration to our docker-compose? or by extending it using the `-f` flag

2024-04-25 13:44 UTC, 0x0elliot requested changes

2024-04-25 13:44 UTC, 0x0elliot commented on functions/onprem/orborus/orborus.go
> +	url := "http://localhost:5160/api/v0/pipeline/create"
This won't work with docker because of networking issues.

2024-04-25 13:44 UTC, 0x0elliot commented on functions/onprem/orborus/orborus.go
> +	url := "http://localhost:5160/api/v0/pipeline/update"
Same here

2024-04-25 13:44 UTC, 0x0elliot commented on functions/onprem/orborus/orborus.go
> +	url := "http://localhost:5160/api/v0/pipeline/delete"
Same here

2024-04-25 13:44 UTC, 0x0elliot commented on functions/onprem/orborus/orborus.go
> +	url := "http://localhost:5160/api/v0/pipeline/list"
Same here

2024-04-25 13:44 UTC, 0x0elliot commented on functions/onprem/orborus/orborus.go
> +	fullUrl := "https://opulent-orbit-979qvgvgx6rvfx7qp-5001.app.github.dev/api/v1/triggers/pipeline/save"
Don't forget to remove this

2024-04-25 13:44 UTC, 0x0elliot commented
Please remember this!

<img width="1083" alt="Screenshot 2024-04-25 at 7 14 20 PM" src="https://github.com/Shuffle/Shuffle/assets/60684641/11296e8f-3638-4085-bc6c-4ce33999ccdd">

2024-04-25 14:13 UTC, frikky commented
> If i were you, I would have tried to figure out if there is a way to add the tenzir configuration to our docker-compose? or by extending it using the `-f` flag. You can also create a tenzir override, like this: https://github.com/intelowlproject/IntelOwl/blob/master/docker/elasticsearch.override.yml

Do NOT do this. The whole point is to have it as an addition, and not a necessity. Any necessity creates further potential problems we HAVE to fix instead of maybe need to fix.

2024-04-26 05:52 UTC, closed without merging

2024-04-26 06:08 UTC, 0x0elliot commented
@frikky i don't think i got my point across! the whole point of docker compose overrides is to have additional optional services. 

that's why using them takes an extra argument while using the docker-compose utility.

2024-04-26 15:55 UTC, frikky commented
> @frikky i don't think i got my point across! the whole point of docker compose overrides is to have additional optional services.
> 
> that's why using them takes an extra argument while using the docker-compose utility.

The problem with this is still that it requires us to explain it, rather than it just doing it on itself when necessary. I don't think Tenzir (or any 3rd party) as a part of our default setup is a good idea, and I surely don't want to teach people about how docker, docker-compose or k8s works.  

Making it code-controlled is a 100% of the time the better option (if you have time), as that is a part that we are in control of and can optimise over time. And in our case, we're not adding this JUST to have a pipeline system. We're adding it, as it gives us access to additional functionality we wouldn't have otherwise.

2024-04-26 17:58 UTC, 0x0elliot commented
I agree. I didn't see it being code controlled anywhere so I assumed somethings. You're right, our philosophy should always make it code controlled.