[Feature] Add Endpoint for Hotloading Specific Applications
Shuffle/Shuffle pull request #1452
Opened 2024-07-14 10:15 UTC by melv33n

### Description
This pull request introduces a new endpoint to the backend API that allows hotloading a specific application. Instead of hotloading or refreshing all applications in the apps directory, the new endpoint targets a specific application using the appName.

**New Endpoint**:
`GET apps/{appName}/run_hotload`

**Related Issue and Comment**:
Refer to my comment on this issue: [https://github.com/Shuffle/Shuffle/issues/1450#issuecomment-2214513175](https://github.com/Shuffle/Shuffle/issues/1450#issuecomment-2214513175).

**Additional Changes in `install-guide.md`**:
- Added environment HOTLOAD variables.
- Fixed old password value.
- Hostname change to Docker IP inspection

Sry for the indentation fixes.

2024-10-23 10:42 UTC, P4sca1 requested changes

2024-10-23 10:42 UTC, P4sca1 commented on backend/go-app/main.go
> +	r.HandleFunc("/api/v1/apps/{appName}/run_hotload", handleSingleAppHotloadRequest).Methods("GET", "OPTIONS")
GET requests should not perform operations that modify state.

2024-10-30 12:10 UTC, frikky commented
@melv33n could you send this PR to the 2.0.0 branch, and remove your changes to the run.sh script? We want the backend code to be checking everything itself and to output bugs, not to require a more and more complex bash script on top during testing. 

With that, we'll merge this immediately :)

2024-10-30 18:01 UTC, melv33n commented
> @melv33n could you send this PR to the 2.0.0 branch, and remove your changes to the run.sh script? We want the backend code to be checking everything itself and to output bugs, not to require a more and more complex bash script on top during testing.
> 
> Oh, and what @P4sca1 said: **add** POST as an option to both hotloads. We are moving towards standardizing more for the v2 API in the future, and will get these things fixed :)
> 
> With that, we'll merge this immediately

Closing this PR in favor of the updated PR #[1538](https://github.com/Shuffle/Shuffle/pull/1538), which includes requested changes and aligns with the 2.0.0 branch.

2024-10-30 18:01 UTC, closed without merging